/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArcadeProAvatarV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "balanceOf"
      | "dnaHashById"
      | "getApproved"
      | "isApprovedForAll"
      | "isProActive"
      | "lifetimeCutoff"
      | "membershipExpiresAtById"
      | "membershipTierById"
      | "mintFromRouter"
      | "name"
      | "nextTokenId"
      | "nicknameById"
      | "owner"
      | "ownerOf"
      | "paymentsRouter"
      | "proStatus"
      | "renewFromRouter"
      | "renounceOwnership"
      | "setApprovalForAll"
      | "setLifetimeCutoff"
      | "setPaymentsRouter"
      | "setTransfersUnlocked"
      | "symbol"
      | "tokenIdByOwner"
      | "tokenURI"
      | "tokenURIById"
      | "transferFrom"
      | "transferOwnership"
      | "transfersUnlocked"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "LifetimeCutoffSet"
      | "OwnershipTransferred"
      | "ProMinted"
      | "ProRenewed"
      | "RouterSet"
      | "Transfer"
      | "TransfersUnlockedSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dnaHashById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lifetimeCutoff",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "membershipExpiresAtById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "membershipTierById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintFromRouter",
    values: [AddressLike, BigNumberish, string, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nicknameById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentsRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renewFromRouter",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setLifetimeCutoff",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentsRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransfersUnlocked",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenIdByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURIById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfersUnlocked",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dnaHashById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lifetimeCutoff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "membershipExpiresAtById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "membershipTierById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintFromRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nicknameById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentsRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewFromRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLifetimeCutoff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentsRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransfersUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenURIById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transfersUnlocked",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    id: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, id: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LifetimeCutoffSetEvent {
  export type InputTuple = [cutoff: BigNumberish];
  export type OutputTuple = [cutoff: bigint];
  export interface OutputObject {
    cutoff: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    tier: BigNumberish,
    expiresAt: BigNumberish,
    nickname: string
  ];
  export type OutputTuple = [
    user: string,
    tokenId: bigint,
    tier: bigint,
    expiresAt: bigint,
    nickname: string
  ];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    tier: bigint;
    expiresAt: bigint;
    nickname: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenId: BigNumberish,
    tier: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenId: bigint,
    tier: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
    tier: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterSetEvent {
  export type InputTuple = [router: AddressLike];
  export type OutputTuple = [router: string];
  export interface OutputObject {
    router: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, id: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransfersUnlockedSetEvent {
  export type InputTuple = [unlocked: boolean];
  export type OutputTuple = [unlocked: boolean];
  export interface OutputObject {
    unlocked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcadeProAvatarV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ArcadeProAvatarV2;
  waitForDeployment(): Promise<this>;

  interface: ArcadeProAvatarV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<
    [spender: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner_: AddressLike], [bigint], "view">;

  dnaHashById: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getApproved: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  isApprovedForAll: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isProActive: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  lifetimeCutoff: TypedContractMethod<[], [bigint], "view">;

  membershipExpiresAtById: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  membershipTierById: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  mintFromRouter: TypedContractMethod<
    [
      to: AddressLike,
      tier: BigNumberish,
      _tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  nicknameById: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[id: BigNumberish], [string], "view">;

  paymentsRouter: TypedContractMethod<[], [string], "view">;

  proStatus: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        tokenId: bigint;
        tier: bigint;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  renewFromRouter: TypedContractMethod<
    [user: AddressLike, tier: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setLifetimeCutoff: TypedContractMethod<
    [cutoff: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentsRouter: TypedContractMethod<
    [router: AddressLike],
    [void],
    "nonpayable"
  >;

  setTransfersUnlocked: TypedContractMethod<
    [unlocked: boolean],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenIdByOwner: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tokenURI: TypedContractMethod<[id: BigNumberish], [string], "view">;

  tokenURIById: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transfersUnlocked: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner_: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dnaHashById"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProActive"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lifetimeCutoff"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "membershipExpiresAtById"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "membershipTierById"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintFromRouter"
  ): TypedContractMethod<
    [
      to: AddressLike,
      tier: BigNumberish,
      _tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nicknameById"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "paymentsRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proStatus"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        tokenId: bigint;
        tier: bigint;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renewFromRouter"
  ): TypedContractMethod<
    [user: AddressLike, tier: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLifetimeCutoff"
  ): TypedContractMethod<[cutoff: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentsRouter"
  ): TypedContractMethod<[router: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTransfersUnlocked"
  ): TypedContractMethod<[unlocked: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenIdByOwner"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURIById"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, id: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfersUnlocked"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "LifetimeCutoffSet"
  ): TypedContractEvent<
    LifetimeCutoffSetEvent.InputTuple,
    LifetimeCutoffSetEvent.OutputTuple,
    LifetimeCutoffSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProMinted"
  ): TypedContractEvent<
    ProMintedEvent.InputTuple,
    ProMintedEvent.OutputTuple,
    ProMintedEvent.OutputObject
  >;
  getEvent(
    key: "ProRenewed"
  ): TypedContractEvent<
    ProRenewedEvent.InputTuple,
    ProRenewedEvent.OutputTuple,
    ProRenewedEvent.OutputObject
  >;
  getEvent(
    key: "RouterSet"
  ): TypedContractEvent<
    RouterSetEvent.InputTuple,
    RouterSetEvent.OutputTuple,
    RouterSetEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TransfersUnlockedSet"
  ): TypedContractEvent<
    TransfersUnlockedSetEvent.InputTuple,
    TransfersUnlockedSetEvent.OutputTuple,
    TransfersUnlockedSetEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "LifetimeCutoffSet(uint64)": TypedContractEvent<
      LifetimeCutoffSetEvent.InputTuple,
      LifetimeCutoffSetEvent.OutputTuple,
      LifetimeCutoffSetEvent.OutputObject
    >;
    LifetimeCutoffSet: TypedContractEvent<
      LifetimeCutoffSetEvent.InputTuple,
      LifetimeCutoffSetEvent.OutputTuple,
      LifetimeCutoffSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProMinted(address,uint256,uint8,uint64,string)": TypedContractEvent<
      ProMintedEvent.InputTuple,
      ProMintedEvent.OutputTuple,
      ProMintedEvent.OutputObject
    >;
    ProMinted: TypedContractEvent<
      ProMintedEvent.InputTuple,
      ProMintedEvent.OutputTuple,
      ProMintedEvent.OutputObject
    >;

    "ProRenewed(address,uint256,uint8,uint64)": TypedContractEvent<
      ProRenewedEvent.InputTuple,
      ProRenewedEvent.OutputTuple,
      ProRenewedEvent.OutputObject
    >;
    ProRenewed: TypedContractEvent<
      ProRenewedEvent.InputTuple,
      ProRenewedEvent.OutputTuple,
      ProRenewedEvent.OutputObject
    >;

    "RouterSet(address)": TypedContractEvent<
      RouterSetEvent.InputTuple,
      RouterSetEvent.OutputTuple,
      RouterSetEvent.OutputObject
    >;
    RouterSet: TypedContractEvent<
      RouterSetEvent.InputTuple,
      RouterSetEvent.OutputTuple,
      RouterSetEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TransfersUnlockedSet(bool)": TypedContractEvent<
      TransfersUnlockedSetEvent.InputTuple,
      TransfersUnlockedSetEvent.OutputTuple,
      TransfersUnlockedSetEvent.OutputObject
    >;
    TransfersUnlockedSet: TypedContractEvent<
      TransfersUnlockedSetEvent.InputTuple,
      TransfersUnlockedSetEvent.OutputTuple,
      TransfersUnlockedSetEvent.OutputObject
    >;
  };
}
