/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as arcadePaymentsRouterV2Sol from "./ArcadePaymentsRouterV2.sol";
export type { arcadePaymentsRouterV2Sol };
import type * as arcadeTreasuryVaultSol from "./ArcadeTreasuryVault.sol";
export type { arcadeTreasuryVaultSol };
export type { ArcadeEpochVault } from "./ArcadeEpochVault";
export type { ArcadeProAvatarV2 } from "./ArcadeProAvatarV2";
export type { ArcadePromo } from "./ArcadePromo";
export type { MockERC20 } from "./MockERC20";
