/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ArcadeTreasuryVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH"
      | "autoConvertToken"
      | "batchWithdrawERC20"
      | "batchWithdrawETH"
      | "exactOutPathToMUSD"
      | "fundVaultMUSD"
      | "keeper"
      | "mUSD"
      | "maxSwapIn"
      | "owner"
      | "payoutVault"
      | "renounceOwnership"
      | "reserveToken"
      | "setAutoConvertToken"
      | "setExactOutPathToMUSD"
      | "setKeeper"
      | "setMaxSwapIn"
      | "setPayoutVault"
      | "setReserveToken"
      | "setSwapConfig"
      | "swapETHForExactMUSDToVault"
      | "swapRouter"
      | "swapTokenForExactMUSDToVault"
      | "transferOwnership"
      | "withdrawERC20"
      | "withdrawETH"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoConvertTokenSet"
      | "ExactOutPathSet"
      | "KeeperSet"
      | "MaxSwapInSet"
      | "OwnershipTransferred"
      | "PayoutVaultSet"
      | "ReserveTokenSet"
      | "SwapConfigSet"
      | "TreasuryBatchWithdrawERC20"
      | "TreasuryBatchWithdrawETH"
      | "TreasuryFundedVault"
      | "TreasurySwapToMUSD"
      | "TreasuryWithdrawERC20"
      | "TreasuryWithdrawETH"
  ): EventFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "autoConvertToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWithdrawERC20",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWithdrawETH",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "exactOutPathToMUSD",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundVaultMUSD",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(functionFragment: "mUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxSwapIn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoConvertToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setExactOutPathToMUSD",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSwapIn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPayoutVault",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapConfig",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHForExactMUSDToVault",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokenForExactMUSDToVault",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "autoConvertToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchWithdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exactOutPathToMUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundVaultMUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mUSD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxSwapIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoConvertToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExactOutPathToMUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSwapIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPayoutVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForExactMUSDToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapTokenForExactMUSDToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
}

export namespace AutoConvertTokenSetEvent {
  export type InputTuple = [token: AddressLike, enabled: boolean];
  export type OutputTuple = [token: string, enabled: boolean];
  export interface OutputObject {
    token: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExactOutPathSetEvent {
  export type InputTuple = [tokenIn: AddressLike, path: BytesLike];
  export type OutputTuple = [tokenIn: string, path: string];
  export interface OutputObject {
    tokenIn: string;
    path: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperSetEvent {
  export type InputTuple = [oldKeeper: AddressLike, newKeeper: AddressLike];
  export type OutputTuple = [oldKeeper: string, newKeeper: string];
  export interface OutputObject {
    oldKeeper: string;
    newKeeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxSwapInSetEvent {
  export type InputTuple = [tokenIn: AddressLike, maxAmountIn: BigNumberish];
  export type OutputTuple = [tokenIn: string, maxAmountIn: bigint];
  export interface OutputObject {
    tokenIn: string;
    maxAmountIn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutVaultSetEvent {
  export type InputTuple = [vault: AddressLike, allowed: boolean];
  export type OutputTuple = [vault: string, allowed: boolean];
  export interface OutputObject {
    vault: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveTokenSetEvent {
  export type InputTuple = [token: AddressLike, enabled: boolean];
  export type OutputTuple = [token: string, enabled: boolean];
  export interface OutputObject {
    token: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapConfigSetEvent {
  export type InputTuple = [
    mUSD: AddressLike,
    WETH: AddressLike,
    router: AddressLike
  ];
  export type OutputTuple = [mUSD: string, WETH: string, router: string];
  export interface OutputObject {
    mUSD: string;
    WETH: string;
    router: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryBatchWithdrawERC20Event {
  export type InputTuple = [
    token: AddressLike,
    count: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [token: string, count: bigint, totalAmount: bigint];
  export interface OutputObject {
    token: string;
    count: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryBatchWithdrawETHEvent {
  export type InputTuple = [count: BigNumberish, totalAmount: BigNumberish];
  export type OutputTuple = [count: bigint, totalAmount: bigint];
  export interface OutputObject {
    count: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryFundedVaultEvent {
  export type InputTuple = [payoutVault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [payoutVault: string, amount: bigint];
  export interface OutputObject {
    payoutVault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySwapToMUSDEvent {
  export type InputTuple = [
    tokenIn: AddressLike,
    payoutVault: AddressLike,
    amountInUsed: BigNumberish,
    amountOut: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    tokenIn: string,
    payoutVault: string,
    amountInUsed: bigint,
    amountOut: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    tokenIn: string;
    payoutVault: string;
    amountInUsed: bigint;
    amountOut: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryWithdrawERC20Event {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryWithdrawETHEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcadeTreasuryVault extends BaseContract {
  connect(runner?: ContractRunner | null): ArcadeTreasuryVault;
  waitForDeployment(): Promise<this>;

  interface: ArcadeTreasuryVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH: TypedContractMethod<[], [string], "view">;

  autoConvertToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  batchWithdrawERC20: TypedContractMethod<
    [token: AddressLike, to: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchWithdrawETH: TypedContractMethod<
    [to: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  exactOutPathToMUSD: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  fundVaultMUSD: TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  keeper: TypedContractMethod<[], [string], "view">;

  mUSD: TypedContractMethod<[], [string], "view">;

  maxSwapIn: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payoutVault: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setAutoConvertToken: TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setExactOutPathToMUSD: TypedContractMethod<
    [tokenIn: AddressLike, path: BytesLike],
    [void],
    "nonpayable"
  >;

  setKeeper: TypedContractMethod<
    [newKeeper: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxSwapIn: TypedContractMethod<
    [tokenIn: AddressLike, maxAmountIn: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPayoutVault: TypedContractMethod<
    [vault: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setReserveToken: TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setSwapConfig: TypedContractMethod<
    [_mUSD: AddressLike, _WETH: AddressLike, _router: AddressLike],
    [void],
    "nonpayable"
  >;

  swapETHForExactMUSDToVault: TypedContractMethod<
    [
      vault: AddressLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapRouter: TypedContractMethod<[], [string], "view">;

  swapTokenForExactMUSDToVault: TypedContractMethod<
    [
      tokenIn: AddressLike,
      vault: AddressLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawERC20: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "autoConvertToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchWithdrawERC20"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchWithdrawETH"
  ): TypedContractMethod<
    [to: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exactOutPathToMUSD"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "fundVaultMUSD"
  ): TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "keeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxSwapIn"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutVault"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAutoConvertToken"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setExactOutPathToMUSD"
  ): TypedContractMethod<
    [tokenIn: AddressLike, path: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<[newKeeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxSwapIn"
  ): TypedContractMethod<
    [tokenIn: AddressLike, maxAmountIn: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPayoutVault"
  ): TypedContractMethod<
    [vault: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveToken"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSwapConfig"
  ): TypedContractMethod<
    [_mUSD: AddressLike, _WETH: AddressLike, _router: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapETHForExactMUSDToVault"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapTokenForExactMUSDToVault"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      vault: AddressLike,
      amountOut: BigNumberish,
      amountInMaximum: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawERC20"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AutoConvertTokenSet"
  ): TypedContractEvent<
    AutoConvertTokenSetEvent.InputTuple,
    AutoConvertTokenSetEvent.OutputTuple,
    AutoConvertTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "ExactOutPathSet"
  ): TypedContractEvent<
    ExactOutPathSetEvent.InputTuple,
    ExactOutPathSetEvent.OutputTuple,
    ExactOutPathSetEvent.OutputObject
  >;
  getEvent(
    key: "KeeperSet"
  ): TypedContractEvent<
    KeeperSetEvent.InputTuple,
    KeeperSetEvent.OutputTuple,
    KeeperSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxSwapInSet"
  ): TypedContractEvent<
    MaxSwapInSetEvent.InputTuple,
    MaxSwapInSetEvent.OutputTuple,
    MaxSwapInSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutVaultSet"
  ): TypedContractEvent<
    PayoutVaultSetEvent.InputTuple,
    PayoutVaultSetEvent.OutputTuple,
    PayoutVaultSetEvent.OutputObject
  >;
  getEvent(
    key: "ReserveTokenSet"
  ): TypedContractEvent<
    ReserveTokenSetEvent.InputTuple,
    ReserveTokenSetEvent.OutputTuple,
    ReserveTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "SwapConfigSet"
  ): TypedContractEvent<
    SwapConfigSetEvent.InputTuple,
    SwapConfigSetEvent.OutputTuple,
    SwapConfigSetEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryBatchWithdrawERC20"
  ): TypedContractEvent<
    TreasuryBatchWithdrawERC20Event.InputTuple,
    TreasuryBatchWithdrawERC20Event.OutputTuple,
    TreasuryBatchWithdrawERC20Event.OutputObject
  >;
  getEvent(
    key: "TreasuryBatchWithdrawETH"
  ): TypedContractEvent<
    TreasuryBatchWithdrawETHEvent.InputTuple,
    TreasuryBatchWithdrawETHEvent.OutputTuple,
    TreasuryBatchWithdrawETHEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryFundedVault"
  ): TypedContractEvent<
    TreasuryFundedVaultEvent.InputTuple,
    TreasuryFundedVaultEvent.OutputTuple,
    TreasuryFundedVaultEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySwapToMUSD"
  ): TypedContractEvent<
    TreasurySwapToMUSDEvent.InputTuple,
    TreasurySwapToMUSDEvent.OutputTuple,
    TreasurySwapToMUSDEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryWithdrawERC20"
  ): TypedContractEvent<
    TreasuryWithdrawERC20Event.InputTuple,
    TreasuryWithdrawERC20Event.OutputTuple,
    TreasuryWithdrawERC20Event.OutputObject
  >;
  getEvent(
    key: "TreasuryWithdrawETH"
  ): TypedContractEvent<
    TreasuryWithdrawETHEvent.InputTuple,
    TreasuryWithdrawETHEvent.OutputTuple,
    TreasuryWithdrawETHEvent.OutputObject
  >;

  filters: {
    "AutoConvertTokenSet(address,bool)": TypedContractEvent<
      AutoConvertTokenSetEvent.InputTuple,
      AutoConvertTokenSetEvent.OutputTuple,
      AutoConvertTokenSetEvent.OutputObject
    >;
    AutoConvertTokenSet: TypedContractEvent<
      AutoConvertTokenSetEvent.InputTuple,
      AutoConvertTokenSetEvent.OutputTuple,
      AutoConvertTokenSetEvent.OutputObject
    >;

    "ExactOutPathSet(address,bytes)": TypedContractEvent<
      ExactOutPathSetEvent.InputTuple,
      ExactOutPathSetEvent.OutputTuple,
      ExactOutPathSetEvent.OutputObject
    >;
    ExactOutPathSet: TypedContractEvent<
      ExactOutPathSetEvent.InputTuple,
      ExactOutPathSetEvent.OutputTuple,
      ExactOutPathSetEvent.OutputObject
    >;

    "KeeperSet(address,address)": TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;
    KeeperSet: TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;

    "MaxSwapInSet(address,uint256)": TypedContractEvent<
      MaxSwapInSetEvent.InputTuple,
      MaxSwapInSetEvent.OutputTuple,
      MaxSwapInSetEvent.OutputObject
    >;
    MaxSwapInSet: TypedContractEvent<
      MaxSwapInSetEvent.InputTuple,
      MaxSwapInSetEvent.OutputTuple,
      MaxSwapInSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutVaultSet(address,bool)": TypedContractEvent<
      PayoutVaultSetEvent.InputTuple,
      PayoutVaultSetEvent.OutputTuple,
      PayoutVaultSetEvent.OutputObject
    >;
    PayoutVaultSet: TypedContractEvent<
      PayoutVaultSetEvent.InputTuple,
      PayoutVaultSetEvent.OutputTuple,
      PayoutVaultSetEvent.OutputObject
    >;

    "ReserveTokenSet(address,bool)": TypedContractEvent<
      ReserveTokenSetEvent.InputTuple,
      ReserveTokenSetEvent.OutputTuple,
      ReserveTokenSetEvent.OutputObject
    >;
    ReserveTokenSet: TypedContractEvent<
      ReserveTokenSetEvent.InputTuple,
      ReserveTokenSetEvent.OutputTuple,
      ReserveTokenSetEvent.OutputObject
    >;

    "SwapConfigSet(address,address,address)": TypedContractEvent<
      SwapConfigSetEvent.InputTuple,
      SwapConfigSetEvent.OutputTuple,
      SwapConfigSetEvent.OutputObject
    >;
    SwapConfigSet: TypedContractEvent<
      SwapConfigSetEvent.InputTuple,
      SwapConfigSetEvent.OutputTuple,
      SwapConfigSetEvent.OutputObject
    >;

    "TreasuryBatchWithdrawERC20(address,uint256,uint256)": TypedContractEvent<
      TreasuryBatchWithdrawERC20Event.InputTuple,
      TreasuryBatchWithdrawERC20Event.OutputTuple,
      TreasuryBatchWithdrawERC20Event.OutputObject
    >;
    TreasuryBatchWithdrawERC20: TypedContractEvent<
      TreasuryBatchWithdrawERC20Event.InputTuple,
      TreasuryBatchWithdrawERC20Event.OutputTuple,
      TreasuryBatchWithdrawERC20Event.OutputObject
    >;

    "TreasuryBatchWithdrawETH(uint256,uint256)": TypedContractEvent<
      TreasuryBatchWithdrawETHEvent.InputTuple,
      TreasuryBatchWithdrawETHEvent.OutputTuple,
      TreasuryBatchWithdrawETHEvent.OutputObject
    >;
    TreasuryBatchWithdrawETH: TypedContractEvent<
      TreasuryBatchWithdrawETHEvent.InputTuple,
      TreasuryBatchWithdrawETHEvent.OutputTuple,
      TreasuryBatchWithdrawETHEvent.OutputObject
    >;

    "TreasuryFundedVault(address,uint256)": TypedContractEvent<
      TreasuryFundedVaultEvent.InputTuple,
      TreasuryFundedVaultEvent.OutputTuple,
      TreasuryFundedVaultEvent.OutputObject
    >;
    TreasuryFundedVault: TypedContractEvent<
      TreasuryFundedVaultEvent.InputTuple,
      TreasuryFundedVaultEvent.OutputTuple,
      TreasuryFundedVaultEvent.OutputObject
    >;

    "TreasurySwapToMUSD(address,address,uint256,uint256,uint256)": TypedContractEvent<
      TreasurySwapToMUSDEvent.InputTuple,
      TreasurySwapToMUSDEvent.OutputTuple,
      TreasurySwapToMUSDEvent.OutputObject
    >;
    TreasurySwapToMUSD: TypedContractEvent<
      TreasurySwapToMUSDEvent.InputTuple,
      TreasurySwapToMUSDEvent.OutputTuple,
      TreasurySwapToMUSDEvent.OutputObject
    >;

    "TreasuryWithdrawERC20(address,address,uint256)": TypedContractEvent<
      TreasuryWithdrawERC20Event.InputTuple,
      TreasuryWithdrawERC20Event.OutputTuple,
      TreasuryWithdrawERC20Event.OutputObject
    >;
    TreasuryWithdrawERC20: TypedContractEvent<
      TreasuryWithdrawERC20Event.InputTuple,
      TreasuryWithdrawERC20Event.OutputTuple,
      TreasuryWithdrawERC20Event.OutputObject
    >;

    "TreasuryWithdrawETH(address,uint256)": TypedContractEvent<
      TreasuryWithdrawETHEvent.InputTuple,
      TreasuryWithdrawETHEvent.OutputTuple,
      TreasuryWithdrawETHEvent.OutputObject
    >;
    TreasuryWithdrawETH: TypedContractEvent<
      TreasuryWithdrawETHEvent.InputTuple,
      TreasuryWithdrawETHEvent.OutputTuple,
      TreasuryWithdrawETHEvent.OutputObject
    >;
  };
}
