/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IArcadeProAvatarV2,
  IArcadeProAvatarV2Interface,
} from "../../../contracts/ArcadePaymentsRouterV2.sol/IArcadeProAvatarV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "tier",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "dnaHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "nickname",
        type: "string",
      },
    ],
    name: "mintFromRouter",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "tier",
        type: "uint8",
      },
    ],
    name: "renewFromRouter",
    outputs: [
      {
        internalType: "uint64",
        name: "newExpiresAt",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IArcadeProAvatarV2__factory {
  static readonly abi = _abi;
  static createInterface(): IArcadeProAvatarV2Interface {
    return new Interface(_abi) as IArcadeProAvatarV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IArcadeProAvatarV2 {
    return new Contract(address, _abi, runner) as unknown as IArcadeProAvatarV2;
  }
}
