/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArcadePaymentsRouterV2 {
  export type QuoteStruct = {
    buyer: AddressLike;
    sku: BytesLike;
    kind: BigNumberish;
    payToken: AddressLike;
    amountIn: BigNumberish;
    usdCents: BigNumberish;
    credits: BigNumberish;
    tier: BigNumberish;
    expiresAt: BigNumberish;
    nonce: BigNumberish;
    ref: BytesLike;
    dataHash: BytesLike;
  };

  export type QuoteStructOutput = [
    buyer: string,
    sku: string,
    kind: bigint,
    payToken: string,
    amountIn: bigint,
    usdCents: bigint,
    credits: bigint,
    tier: bigint,
    expiresAt: bigint,
    nonce: bigint,
    ref: string,
    dataHash: string
  ] & {
    buyer: string;
    sku: string;
    kind: bigint;
    payToken: string;
    amountIn: bigint;
    usdCents: bigint;
    credits: bigint;
    tier: bigint;
    expiresAt: bigint;
    nonce: bigint;
    ref: string;
    dataHash: string;
  };

  export type SplitBpsStruct = {
    opsBps: BigNumberish;
    dailyBps: BigNumberish;
    weeklyBps: BigNumberish;
    treasuryBps: BigNumberish;
  };

  export type SplitBpsStructOutput = [
    opsBps: bigint,
    dailyBps: bigint,
    weeklyBps: bigint,
    treasuryBps: bigint
  ] & {
    opsBps: bigint;
    dailyBps: bigint;
    weeklyBps: bigint;
    treasuryBps: bigint;
  };
}

export interface ArcadePaymentsRouterV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "EIP712_NAME"
      | "EIP712_VERSION"
      | "KIND_CREDITS"
      | "KIND_GENERIC"
      | "KIND_NONE"
      | "KIND_PRO_MINT"
      | "KIND_PRO_RENEW"
      | "dailyPot"
      | "directOpsToken"
      | "eip712Domain"
      | "getTokenList"
      | "kindSplits"
      | "mUSD"
      | "mintProAvatar"
      | "opsWallet"
      | "owner"
      | "paused"
      | "payOnly"
      | "proAvatar"
      | "processPayment"
      | "purchaseCredits"
      | "quoteDigest"
      | "quoteSigner"
      | "renewPro"
      | "renounceOwnership"
      | "rescueERC20"
      | "rescueETH"
      | "setDirectOpsToken"
      | "setKindSplits"
      | "setPaused"
      | "setProAvatar"
      | "setQuoteSigner"
      | "setRecipients"
      | "setSkuKind"
      | "setTokenAllowed"
      | "setTreasuryVault"
      | "skuKind"
      | "tokenAllowed"
      | "tokenListCount"
      | "transferOwnership"
      | "treasuryVault"
      | "usedQuote"
      | "weeklyPot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreditsPurchased"
      | "DirectOpsTokenSet"
      | "EIP712DomainChanged"
      | "KindSplitsSet"
      | "OwnershipTransferred"
      | "PausedSet"
      | "PaymentExecuted"
      | "ProAvatarSet"
      | "ProMinted"
      | "ProRenewed"
      | "QuoteSignerSet"
      | "RecipientsSet"
      | "SkuKindSet"
      | "TokenAllowed"
      | "TreasuryVaultSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EIP712_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EIP712_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_CREDITS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_GENERIC",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "KIND_NONE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "KIND_PRO_MINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_PRO_RENEW",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dailyPot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "directOpsToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kindSplits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintProAvatar",
    values: [
      ArcadePaymentsRouterV2.QuoteStruct,
      BytesLike,
      string,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "opsWallet", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payOnly",
    values: [ArcadePaymentsRouterV2.QuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "proAvatar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [ArcadePaymentsRouterV2.QuoteStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCredits",
    values: [ArcadePaymentsRouterV2.QuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDigest",
    values: [ArcadePaymentsRouterV2.QuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renewPro",
    values: [ArcadePaymentsRouterV2.QuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDirectOpsToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setKindSplits",
    values: [BigNumberish, ArcadePaymentsRouterV2.SplitBpsStruct]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setProAvatar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecipients",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSkuKind",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "skuKind", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "tokenAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenListCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedQuote",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "weeklyPot", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "EIP712_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EIP712_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_CREDITS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_GENERIC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KIND_NONE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KIND_PRO_MINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_PRO_RENEW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyPot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "directOpsToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kindSplits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintProAvatar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "opsWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payOnly", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proAvatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "renewPro", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rescueETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDirectOpsToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKindSplits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProAvatar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSkuKind", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "skuKind", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenListCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedQuote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weeklyPot", data: BytesLike): Result;
}

export namespace CreditsPurchasedEvent {
  export type InputTuple = [
    quoteId: BytesLike,
    buyer: AddressLike,
    credits: BigNumberish,
    usdCents: BigNumberish,
    ref: BytesLike
  ];
  export type OutputTuple = [
    quoteId: string,
    buyer: string,
    credits: bigint,
    usdCents: bigint,
    ref: string
  ];
  export interface OutputObject {
    quoteId: string;
    buyer: string;
    credits: bigint;
    usdCents: bigint;
    ref: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectOpsTokenSetEvent {
  export type InputTuple = [token: AddressLike, enabled: boolean];
  export type OutputTuple = [token: string, enabled: boolean];
  export interface OutputObject {
    token: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KindSplitsSetEvent {
  export type InputTuple = [
    kind: BigNumberish,
    opsBps: BigNumberish,
    dailyBps: BigNumberish,
    weeklyBps: BigNumberish,
    treasuryBps: BigNumberish
  ];
  export type OutputTuple = [
    kind: bigint,
    opsBps: bigint,
    dailyBps: bigint,
    weeklyBps: bigint,
    treasuryBps: bigint
  ];
  export interface OutputObject {
    kind: bigint;
    opsBps: bigint;
    dailyBps: bigint;
    weeklyBps: bigint;
    treasuryBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedSetEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    quoteId: BytesLike,
    buyer: AddressLike,
    sku: BytesLike,
    kind: BigNumberish,
    payToken: AddressLike,
    amountIn: BigNumberish,
    usdCents: BigNumberish,
    credits: BigNumberish,
    tier: BigNumberish,
    opsAmount: BigNumberish,
    dailyPotAmount: BigNumberish,
    weeklyPotAmount: BigNumberish,
    treasuryAmount: BigNumberish,
    opsRouted: BigNumberish,
    treasuryRouted: BigNumberish,
    directPotFunding: boolean,
    ref: BytesLike
  ];
  export type OutputTuple = [
    quoteId: string,
    buyer: string,
    sku: string,
    kind: bigint,
    payToken: string,
    amountIn: bigint,
    usdCents: bigint,
    credits: bigint,
    tier: bigint,
    opsAmount: bigint,
    dailyPotAmount: bigint,
    weeklyPotAmount: bigint,
    treasuryAmount: bigint,
    opsRouted: bigint,
    treasuryRouted: bigint,
    directPotFunding: boolean,
    ref: string
  ];
  export interface OutputObject {
    quoteId: string;
    buyer: string;
    sku: string;
    kind: bigint;
    payToken: string;
    amountIn: bigint;
    usdCents: bigint;
    credits: bigint;
    tier: bigint;
    opsAmount: bigint;
    dailyPotAmount: bigint;
    weeklyPotAmount: bigint;
    treasuryAmount: bigint;
    opsRouted: bigint;
    treasuryRouted: bigint;
    directPotFunding: boolean;
    ref: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProAvatarSetEvent {
  export type InputTuple = [proAvatar: AddressLike];
  export type OutputTuple = [proAvatar: string];
  export interface OutputObject {
    proAvatar: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProMintedEvent {
  export type InputTuple = [
    quoteId: BytesLike,
    buyer: AddressLike,
    tokenId: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: string,
    buyer: string,
    tokenId: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    quoteId: string;
    buyer: string;
    tokenId: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProRenewedEvent {
  export type InputTuple = [
    quoteId: BytesLike,
    buyer: AddressLike,
    tier: BigNumberish,
    newExpiresAt: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: string,
    buyer: string,
    tier: bigint,
    newExpiresAt: bigint
  ];
  export interface OutputObject {
    quoteId: string;
    buyer: string;
    tier: bigint;
    newExpiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteSignerSetEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientsSetEvent {
  export type InputTuple = [
    opsWallet: AddressLike,
    dailyPot: AddressLike,
    weeklyPot: AddressLike
  ];
  export type OutputTuple = [
    opsWallet: string,
    dailyPot: string,
    weeklyPot: string
  ];
  export interface OutputObject {
    opsWallet: string;
    dailyPot: string;
    weeklyPot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SkuKindSetEvent {
  export type InputTuple = [sku: BytesLike, kind: BigNumberish];
  export type OutputTuple = [sku: string, kind: bigint];
  export interface OutputObject {
    sku: string;
    kind: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAllowedEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryVaultSetEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcadePaymentsRouterV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ArcadePaymentsRouterV2;
  waitForDeployment(): Promise<this>;

  interface: ArcadePaymentsRouterV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EIP712_NAME: TypedContractMethod<[], [string], "view">;

  EIP712_VERSION: TypedContractMethod<[], [string], "view">;

  KIND_CREDITS: TypedContractMethod<[], [bigint], "view">;

  KIND_GENERIC: TypedContractMethod<[], [bigint], "view">;

  KIND_NONE: TypedContractMethod<[], [bigint], "view">;

  KIND_PRO_MINT: TypedContractMethod<[], [bigint], "view">;

  KIND_PRO_RENEW: TypedContractMethod<[], [bigint], "view">;

  dailyPot: TypedContractMethod<[], [string], "view">;

  directOpsToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getTokenList: TypedContractMethod<[], [string[]], "view">;

  kindSplits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        opsBps: bigint;
        dailyBps: bigint;
        weeklyBps: bigint;
        treasuryBps: bigint;
      }
    ],
    "view"
  >;

  mUSD: TypedContractMethod<[], [string], "view">;

  mintProAvatar: TypedContractMethod<
    [
      q: ArcadePaymentsRouterV2.QuoteStruct,
      sig: BytesLike,
      tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [[string, bigint] & { quoteId: string; tokenId: bigint }],
    "payable"
  >;

  opsWallet: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payOnly: TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [string],
    "payable"
  >;

  proAvatar: TypedContractMethod<[], [string], "view">;

  processPayment: TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike, data: BytesLike],
    [[string, string] & { quoteId: string; result: string }],
    "payable"
  >;

  purchaseCredits: TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [string],
    "payable"
  >;

  quoteDigest: TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct],
    [string],
    "view"
  >;

  quoteSigner: TypedContractMethod<[], [string], "view">;

  renewPro: TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [[string, bigint] & { quoteId: string; newExpiresAt: bigint }],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueERC20: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rescueETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDirectOpsToken: TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setKindSplits: TypedContractMethod<
    [kind: BigNumberish, splits: ArcadePaymentsRouterV2.SplitBpsStruct],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  setProAvatar: TypedContractMethod<
    [_proAvatar: AddressLike],
    [void],
    "nonpayable"
  >;

  setQuoteSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  setRecipients: TypedContractMethod<
    [_opsWallet: AddressLike, _dailyPot: AddressLike, _weeklyPot: AddressLike],
    [void],
    "nonpayable"
  >;

  setSkuKind: TypedContractMethod<
    [sku: BytesLike, kind: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenAllowed: TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setTreasuryVault: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  skuKind: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  tokenAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenListCount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryVault: TypedContractMethod<[], [string], "view">;

  usedQuote: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  weeklyPot: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EIP712_NAME"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EIP712_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KIND_CREDITS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_GENERIC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_PRO_MINT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_PRO_RENEW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyPot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "directOpsToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "kindSplits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        opsBps: bigint;
        dailyBps: bigint;
        weeklyBps: bigint;
        treasuryBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintProAvatar"
  ): TypedContractMethod<
    [
      q: ArcadePaymentsRouterV2.QuoteStruct,
      sig: BytesLike,
      tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [[string, bigint] & { quoteId: string; tokenId: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "opsWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payOnly"
  ): TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "proAvatar"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike, data: BytesLike],
    [[string, string] & { quoteId: string; result: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "purchaseCredits"
  ): TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "quoteDigest"
  ): TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renewPro"
  ): TypedContractMethod<
    [q: ArcadePaymentsRouterV2.QuoteStruct, sig: BytesLike],
    [[string, bigint] & { quoteId: string; newExpiresAt: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueERC20"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDirectOpsToken"
  ): TypedContractMethod<
    [token: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKindSplits"
  ): TypedContractMethod<
    [kind: BigNumberish, splits: ArcadePaymentsRouterV2.SplitBpsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProAvatar"
  ): TypedContractMethod<[_proAvatar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuoteSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecipients"
  ): TypedContractMethod<
    [_opsWallet: AddressLike, _dailyPot: AddressLike, _weeklyPot: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSkuKind"
  ): TypedContractMethod<
    [sku: BytesLike, kind: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenAllowed"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasuryVault"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "skuKind"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenListCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usedQuote"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "weeklyPot"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CreditsPurchased"
  ): TypedContractEvent<
    CreditsPurchasedEvent.InputTuple,
    CreditsPurchasedEvent.OutputTuple,
    CreditsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "DirectOpsTokenSet"
  ): TypedContractEvent<
    DirectOpsTokenSetEvent.InputTuple,
    DirectOpsTokenSetEvent.OutputTuple,
    DirectOpsTokenSetEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "KindSplitsSet"
  ): TypedContractEvent<
    KindSplitsSetEvent.InputTuple,
    KindSplitsSetEvent.OutputTuple,
    KindSplitsSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PausedSet"
  ): TypedContractEvent<
    PausedSetEvent.InputTuple,
    PausedSetEvent.OutputTuple,
    PausedSetEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProAvatarSet"
  ): TypedContractEvent<
    ProAvatarSetEvent.InputTuple,
    ProAvatarSetEvent.OutputTuple,
    ProAvatarSetEvent.OutputObject
  >;
  getEvent(
    key: "ProMinted"
  ): TypedContractEvent<
    ProMintedEvent.InputTuple,
    ProMintedEvent.OutputTuple,
    ProMintedEvent.OutputObject
  >;
  getEvent(
    key: "ProRenewed"
  ): TypedContractEvent<
    ProRenewedEvent.InputTuple,
    ProRenewedEvent.OutputTuple,
    ProRenewedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteSignerSet"
  ): TypedContractEvent<
    QuoteSignerSetEvent.InputTuple,
    QuoteSignerSetEvent.OutputTuple,
    QuoteSignerSetEvent.OutputObject
  >;
  getEvent(
    key: "RecipientsSet"
  ): TypedContractEvent<
    RecipientsSetEvent.InputTuple,
    RecipientsSetEvent.OutputTuple,
    RecipientsSetEvent.OutputObject
  >;
  getEvent(
    key: "SkuKindSet"
  ): TypedContractEvent<
    SkuKindSetEvent.InputTuple,
    SkuKindSetEvent.OutputTuple,
    SkuKindSetEvent.OutputObject
  >;
  getEvent(
    key: "TokenAllowed"
  ): TypedContractEvent<
    TokenAllowedEvent.InputTuple,
    TokenAllowedEvent.OutputTuple,
    TokenAllowedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryVaultSet"
  ): TypedContractEvent<
    TreasuryVaultSetEvent.InputTuple,
    TreasuryVaultSetEvent.OutputTuple,
    TreasuryVaultSetEvent.OutputObject
  >;

  filters: {
    "CreditsPurchased(bytes32,address,uint256,uint256,bytes32)": TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;
    CreditsPurchased: TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;

    "DirectOpsTokenSet(address,bool)": TypedContractEvent<
      DirectOpsTokenSetEvent.InputTuple,
      DirectOpsTokenSetEvent.OutputTuple,
      DirectOpsTokenSetEvent.OutputObject
    >;
    DirectOpsTokenSet: TypedContractEvent<
      DirectOpsTokenSetEvent.InputTuple,
      DirectOpsTokenSetEvent.OutputTuple,
      DirectOpsTokenSetEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "KindSplitsSet(uint8,uint16,uint16,uint16,uint16)": TypedContractEvent<
      KindSplitsSetEvent.InputTuple,
      KindSplitsSetEvent.OutputTuple,
      KindSplitsSetEvent.OutputObject
    >;
    KindSplitsSet: TypedContractEvent<
      KindSplitsSetEvent.InputTuple,
      KindSplitsSetEvent.OutputTuple,
      KindSplitsSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PausedSet(bool)": TypedContractEvent<
      PausedSetEvent.InputTuple,
      PausedSetEvent.OutputTuple,
      PausedSetEvent.OutputObject
    >;
    PausedSet: TypedContractEvent<
      PausedSetEvent.InputTuple,
      PausedSetEvent.OutputTuple,
      PausedSetEvent.OutputObject
    >;

    "PaymentExecuted(bytes32,address,bytes32,uint8,address,uint256,uint256,uint256,uint8,uint256,uint256,uint256,uint256,uint256,uint256,bool,bytes32)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "ProAvatarSet(address)": TypedContractEvent<
      ProAvatarSetEvent.InputTuple,
      ProAvatarSetEvent.OutputTuple,
      ProAvatarSetEvent.OutputObject
    >;
    ProAvatarSet: TypedContractEvent<
      ProAvatarSetEvent.InputTuple,
      ProAvatarSetEvent.OutputTuple,
      ProAvatarSetEvent.OutputObject
    >;

    "ProMinted(bytes32,address,uint256,uint8)": TypedContractEvent<
      ProMintedEvent.InputTuple,
      ProMintedEvent.OutputTuple,
      ProMintedEvent.OutputObject
    >;
    ProMinted: TypedContractEvent<
      ProMintedEvent.InputTuple,
      ProMintedEvent.OutputTuple,
      ProMintedEvent.OutputObject
    >;

    "ProRenewed(bytes32,address,uint8,uint64)": TypedContractEvent<
      ProRenewedEvent.InputTuple,
      ProRenewedEvent.OutputTuple,
      ProRenewedEvent.OutputObject
    >;
    ProRenewed: TypedContractEvent<
      ProRenewedEvent.InputTuple,
      ProRenewedEvent.OutputTuple,
      ProRenewedEvent.OutputObject
    >;

    "QuoteSignerSet(address)": TypedContractEvent<
      QuoteSignerSetEvent.InputTuple,
      QuoteSignerSetEvent.OutputTuple,
      QuoteSignerSetEvent.OutputObject
    >;
    QuoteSignerSet: TypedContractEvent<
      QuoteSignerSetEvent.InputTuple,
      QuoteSignerSetEvent.OutputTuple,
      QuoteSignerSetEvent.OutputObject
    >;

    "RecipientsSet(address,address,address)": TypedContractEvent<
      RecipientsSetEvent.InputTuple,
      RecipientsSetEvent.OutputTuple,
      RecipientsSetEvent.OutputObject
    >;
    RecipientsSet: TypedContractEvent<
      RecipientsSetEvent.InputTuple,
      RecipientsSetEvent.OutputTuple,
      RecipientsSetEvent.OutputObject
    >;

    "SkuKindSet(bytes32,uint8)": TypedContractEvent<
      SkuKindSetEvent.InputTuple,
      SkuKindSetEvent.OutputTuple,
      SkuKindSetEvent.OutputObject
    >;
    SkuKindSet: TypedContractEvent<
      SkuKindSetEvent.InputTuple,
      SkuKindSetEvent.OutputTuple,
      SkuKindSetEvent.OutputObject
    >;

    "TokenAllowed(address,bool)": TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;
    TokenAllowed: TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;

    "TreasuryVaultSet(address)": TypedContractEvent<
      TreasuryVaultSetEvent.InputTuple,
      TreasuryVaultSetEvent.OutputTuple,
      TreasuryVaultSetEvent.OutputObject
    >;
    TreasuryVaultSet: TypedContractEvent<
      TreasuryVaultSetEvent.InputTuple,
      TreasuryVaultSetEvent.OutputTuple,
      TreasuryVaultSetEvent.OutputObject
    >;
  };
}
