/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IArcadeProAvatarV2Interface extends Interface {
  getFunction(
    nameOrSignature: "mintFromRouter" | "renewFromRouter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mintFromRouter",
    values: [AddressLike, BigNumberish, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renewFromRouter",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "mintFromRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renewFromRouter",
    data: BytesLike
  ): Result;
}

export interface IArcadeProAvatarV2 extends BaseContract {
  connect(runner?: ContractRunner | null): IArcadeProAvatarV2;
  waitForDeployment(): Promise<this>;

  interface: IArcadeProAvatarV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  mintFromRouter: TypedContractMethod<
    [
      to: AddressLike,
      tier: BigNumberish,
      tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [bigint],
    "nonpayable"
  >;

  renewFromRouter: TypedContractMethod<
    [user: AddressLike, tier: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "mintFromRouter"
  ): TypedContractMethod<
    [
      to: AddressLike,
      tier: BigNumberish,
      tokenURI: string,
      dnaHash: BytesLike,
      nickname: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renewFromRouter"
  ): TypedContractMethod<
    [user: AddressLike, tier: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
