// built by gruesøme
// sig (xor5a): 0x382f33362e7a38237a3d282f3f29a2373f

import { Contract, Interface, type Provider } from "ethers";
import type { DeploymentManifestV1 } from "./manifest";

// These JSON files are generated by scripts/exportAbis.ts after `hardhat compile`.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const RouterAbi = require("./generated/abi/ArcadePaymentsRouterV2.abi.json");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const TreasuryAbi = require("./generated/abi/ArcadeTreasuryVault.abi.json");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const EpochVaultAbi = require("./generated/abi/ArcadeEpochVault.abi.json");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const ProAbi = require("./generated/abi/ArcadeProAvatarV2.abi.json");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PromoAbi = require("./generated/abi/ArcadePromo.abi.json");

export function getContracts(params: { manifest: DeploymentManifestV1; provider: Provider }) {
  const { manifest, provider } = params;

  const router = new Contract(manifest.contracts.ArcadePaymentsRouterV2, new Interface(RouterAbi), provider);
  const treasury = new Contract(manifest.contracts.ArcadeTreasuryVault, new Interface(TreasuryAbi), provider);
  const dailyVault = new Contract(manifest.contracts.ArcadeEpochVaultDaily, new Interface(EpochVaultAbi), provider);
  const weeklyVault = new Contract(manifest.contracts.ArcadeEpochVaultWeekly, new Interface(EpochVaultAbi), provider);
  const proAvatar = new Contract(manifest.contracts.ArcadeProAvatarV2, new Interface(ProAbi), provider);
  const promo = new Contract(manifest.contracts.ArcadePromo, new Interface(PromoAbi), provider);

  return { router, treasury, dailyVault, weeklyVault, proAvatar, promo };
}
